spring:
  cloud:
    config:
      auto-refresh: true
      refresh-interval: 60    
      server:
        git:
          uri: https://github.com/azure-samples/spring-petclinic-microservices-config
        native:
          search-locations: classpath:.
  profiles:
    active: native
management:
    endpoints:
         web:
          exposure:
            include:
              - refresh